name: '🐛 bug report'
description: 'create a report to help us squash a bug and improve lumi 🌸'
title: 'bug: <short description>'
labels: ['bug']

body:
  - type: 'textarea'
    id: 'bug-description'
    attributes:
      label: '🐛 describe the bug'
      description: 'a clear and concise description of what the bug is'
    validations:
      required: true

  - type: 'textarea'
    id: 'steps-to-reproduce'
    attributes:
      label: '👣 steps to reproduce'
      description: 'steps to reproduce the behavior'
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: 'textarea'
    id: 'expected-behavior'
    attributes:
      label: '✨ expected behavior'
      description: 'a clear and concise description of what you expected to happen'
    validations:
      required: true

  - type: 'upload'
    id: 'screenshots'
    attributes:
      label: '📸 screenshots or logs'
      description: 'if applicable, add screenshots or terminal logs to help explain your problem'

  - type: 'dropdown'
    id: 'os'
    attributes:
      label: '💻 environment'
      description: 'select the environment(s) where you encountered the bug'
      multiple: true
      options:
        - 'Windows'
        - 'macOS'
        - 'Linux'
        - 'Other (please specify in the description)'
    validations:
      required: true

  - type: 'input'
    id: 'bun-version'
    attributes:
      label: 'bun version'
      description: 'specify the version of bun you are using (e.g., 1.0.0). if you are not using bun, please specify "n/a"'
      placeholder: '1.0.0'
    validations:
      required: true

  - type: 'input'
    id: 'lumi-version'
    attributes:
      label: 'lumi version'
      description: 'specify the version of lumi you are using (e.g., 1.0.0)'
      placeholder: '1.0.0'
    validations:
      required: true

  - type: 'textarea'
    id: 'additional-context'
    attributes:
      label: '✨ additional context'
      description: 'add any other context about the problem here!'

  - type: 'checkboxes'
    id: 'code-of-conduct'
    attributes:
      label: '💖 code of conduct'
      description: 'by submitting this bug, you agree to follow our [code of conduct](/blob/main/CODE_OF_CONDUCT.md)'
      options:
        - label: 'i have read and agree to the code of conduct'
          required: true
