name: auto assign author

run-name: ${{ github.actor }} is automatically assigned to the issue or pr they just opened ✅

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: assign the user who opened the ticket or pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.LUMI_AUTOASSIGN }}
          script: |
            // grab the username of the person who triggered the action
            const author = context.actor

            // tell github's api to assign the ticket to that username
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [author]
            })
