name: auto assign author to issue or pr

run-name: ${{ github.actor }} is automatically assigned to the issue or pr they just opened ✅

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v6
      - name: set up bun
        uses: oven-sh/setup-bun@v2
      - name: install dependencies
        run: bun install
      - name: run bun script to auto-assign the author
        run: bun .github/scripts/auto-assign
        env:
          GITHUB_TOKEN: ${{ secrets.LUMI_AUTOASSIGN }}
