name: sync pull request metadata with issue

run-name: syncing ${{ github.head_ref }} pull request with the linked issue 🔄

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: dump context with js
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context, null, 2))
