name: sync pull request metadata with issue

run-name: syncing ${{ github.ref_name }} pull request with the linked issue 🔄

on:
  pull_request:
    types: [opened]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJson(github) }}
      - run: |
          console.log(JSON.stringify(context, null, 2));
